Adding deepfool linf attack
BorealisAI/advertorch pull request #75
Opened 2020-05-09 16:16 UTC by pbashivan

Added DeepFool Linf attack - https://arxiv.org/abs/1511.04599

2020-05-13 11:27 UTC, gwding commented
@pbashivan Thanks for the contribution! I'll review asap. 
In the mean time, could you add deepfool to different unit tests and also add a benchmark file similar to https://github.com/BorealisAI/advertorch/blob/master/advertorch_examples/attack_benchmarks/benchmark_decoupled_direction_norm.py

https://github.com/BorealisAI/advertorch/blob/master/CONTRIBUTING.md provides some brief guidelines.

Also you might want to put your name for copyright notice at the beginning of the `deepfool.py`

2020-05-13 18:22 UTC, pbashivan commented
@gwding Yes, I'll do that in the next few days.

2020-05-16 21:50 UTC, pbashivan commented
@gwding 
pytest fails on my machine with error: 
`E   ModuleNotFoundError: No module named 'foolbox.attacks.localsearch'` 

I have foolbox 3.0.0 installed. Not sure what the issue is.

2020-05-19 12:45 UTC, gwding commented
@pbashivan Don't worry about this error. These tests was based on an old version of foolbox. Will let you know if there's questions after I review.

2021-07-16 14:57 UTC, msalihs reviewed
Hi @pbashivan! Sorry for this late review. We would like to revive and merge this PR. 

I see that your last two commits are unrelated to the original changes. Can you please revert those commits and do the changes as per the review? If you don't have time, I'd be happy to do them for you. Let me know.

2021-07-16 14:57 UTC, msalihs commented on advertorch/attacks/base.py
> +    def __init__(self, predict, predict_extra, loss_fn, loss_fn_extra, clip_min, clip_max):
Can you revert the changes you've made to the base class?

2021-07-16 14:57 UTC, msalihs commented on advertorch/attacks/deepfool.py
> +      overshoot=0.02, clip_min=0., clip_max=1.):
Add `loss_fn ` as an argument. The argument is needed if you wanna add this attack to unit tests. You can set it None as default.

2021-07-16 14:57 UTC, msalihs commented on advertorch/attacks/deepfool.py
> +        y = replicate_input(y)
What happens if y is None? In some test cases, y is not provided and the tests will fail.

2021-07-16 14:57 UTC, msalihs commented on tests/test_attacks_running.py
> +    DeepfoolLinfAttack: {"n_iter": 5},
Should be `nb_iter`. Or you change the argument name in the class definition of  `DeepfoolLinfAttack`.

2021-07-16 16:10 UTC, masoudhashemi requested changes
Thanks a lot for your contribution and sorry for the very late review. Would you please apply the comments?

2021-07-16 16:10 UTC, masoudhashemi commented on advertorch/attacks/deepfool.py
> +            x = x.clamp_(self.clip_min, self.clip_max).clone().detach().requires_grad_()
would you please use `from advertorch.utils import batch_clamp` instead of `clamp_` so it supports vector clipping?

2021-07-16 16:10 UTC, masoudhashemi commented on advertorch/attacks/deepfool.py
> +    def is_adv(self, logits, y):  # =criterion
would you please change the comments about functions to docstring format?

2021-07-16 16:10 UTC, masoudhashemi commented on advertorch/attacks/deepfool.py
> +              grads.flatten(start_dim=2, end_dim=-1).abs().sum(axis=-1) + 1e-8)  # foolbox code uses start_dim=2 why??
grads has the size of batch_size x (num_classes-1) x *input_shape => this reduces the size to batch_size x (num_classes - 1), as expected. Would you remove the comment or add it on top of the line?

2021-07-29 15:23 UTC, masoudhashemi commented
Closing this PR since an updated version is merged! Thanks, Pouyan!

2021-07-29 15:24 UTC, closed without merging